server:
  port:  ${random.int(10000,10010)}

spring:
  data:
    redis:
      host: 192.168.1.202
      port: 6379
      password: 37D6bf5F2e45d$ef0
      database: 13
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
      timeout: 5000ms





